FORMAT: 1A
HOST: http://growers.whitecrestmushrooms.com/

# Whitecrest Mushrooms

This API lists all the growers associated with a site, sends information about hardware status, and shows data about picking, packing, and mushroom growing.

## Endpoints and API Access

For ItemPath (or any other application) to access data from the grower, an endpoint structure will need to be set up. Either the growers each will need to be connected to the internet and have an endpoint where this API is accesible, or each site will need to have a global processor to take data from the growers and provide a single endpoint to connect to.

## Core Concepts & Routes

* *Grower:* A grower is a single unit consisting of a lift, cart, scale and a packer. Inside a grower there are mushrooms growing on beds, spread over many different vertical levels.
    * *Packer:* The packer is the unit that puts the mushrooms into bins.
    * *Scale:* The scale weighs each packed bin of mushrooms.
    * *Lift:* The lift is the apparatus that moves the harvester between levels.
    * *Harvester:* The robotic arm that grabs mushrooms off of a bed and brings them to a packer.
* *Level:* A level is a collection of beds stacked vertically in a a grower.
* *Bed:* A bed is a soil area on a level where mushrooms are grown.

# Group Growers

A grower is a machine that picks and packs mushrooms.  A grower is a single unit consisting of a lift, cart, scale and a packer. Inside a grower there are mushrooms growing on beds, spread over many different vertical levels. There can be multiple growers on a site.

## Grower [/growers/{id}]


+ Parameters
    + id (number) - The ID of the desired grower.

+ Attributes (object)
    + id (number) - ID of the grower in the form of an integer
    + status (enum[number])
        Status of the grower in the form of an integer
        + Members
            + 0: inactive
            + 1: active
    + name (string) - Descriptor of the grower
    + level_id (number) - ID of the level the grower is positioned at
    + bed_id (number) - ID of the bed the grower is positioned at
    + levels (number) - the number of levels in the grower

### Retrieve a Grower [GET]
Retrieves the Grower with the given ID.

+ Response 200 (application/json)
    + Attributes (Grower)

## Levels [/growers/{id}{?limit}]

+ Attributes (array[Grower])

### List all Growers [GET]
Returns a list of your Growers on a site.

+ Parameters
    + id (number) - the ID of the grower.
    + limit (number, optional)

        A limit on the number of objects to be returned. Limit can range
        between 1 and 100 items.

        + Default: `25`

+ Response 200 (application/json)
    + Attributes (Grower)


# Group Levels

A level is a collection of beds stacked vertically in a a grower.

## Level [/levels/{id}]


+ Parameters
    + id (number) - The ID of the desired level.

+ Attributes (object)
    + id: 1 (number, required)
    + position: 0 (number, required) - vertical location of level
    + beds: [1,2,3,4] (array[number]) - array of bed ID's in level

### Retrieve a Level [GET]
Retrieves the level with the given ID.

+ Response 200 (application/json)
    + Attributes (Level)

## Levels [/grower/{grower_id}/levels{?limit}]

+ Attributes (array[Level])

### List all Levels [GET]
Returns a list of your Levels on a specific grower, in order of position.

+ Parameters
    + grower_id (number) - the ID of the grower.
    + limit (number, optional)

        A limit on the number of objects to be returned. Limit can range
        between 1 and 100 items.

        + Default: `25`

+ Response 200 (application/json)
    + Attributes (Levels)

# Group Beds

A bed is a soil area on a level where mushrooms are grown.

## Bed [/beds/{id}]


+ Parameters
    + id (number) - The ID of the desired bed.

+ Attributes (object)
    + id: 1 (number, required)
    + position: 0 (number, required) - horizontal location of bed on a level
    + width: 24 (number) - width of bed in cm
    + height: 96 (number) - height of bed in cm
    + level_id: 1 (number) - the ID of the level the bed is located on
    + ph: 8 (number) - the current pH level
    + temperature: 276 (number) - the current temperature

### Retrieve a Bed [GET]
Retrieves the level with the given ID.

+ Response 200 (application/json)
    + Attributes (Bed)

## Beds [/beds{?limit}]

+ Attributes (array[Bed])

### List all Beds [GET]
Returns a list of your Beds.

+ Parameters
    + limit (number, optional)

        A limit on the number of objects to be returned. Limit can range
        between 1 and 100 items.

        + Default: `25`

+ Response 200 (application/json)
    + Attributes (Beds)

# Group Mushrooms

A mushroom is located on a bed, in a level, and on a grower.

## Mushroom [/mushrooms/{id}]


+ Parameters
    + id (number) - The ID of the desired mushroom.

+ Attributes (object)
    + id: 1 (number, required)
    + x-coordinate: 14 (number, required) - x position on bed
    + y-coordinate: 35 (number, required) - y position on bed
    + size: 3 (number)
    + rotation: 264 (number) - rotation in degrees
    + is_cluster: true (boolean)
    + maturity_time: 15593060634745 (number) - date stamp of when the mushroom is ready to be picked

### Retrieve a Mushroom [GET]
Retrieves the level with the given ID.

+ Response 200 (application/json)
    + Attributes (Mushroom)

## Mushrooms [/mushrooms{?limit}]

+ Attributes (array[mushrooms])

### List all Mushrooms [GET]
Returns a list of your Mushrooms.

+ Parameters
    + limit (number, optional)

        A limit on the number of objects to be returned. Limit can range
        between 1 and 500 items.

        + Default: `50`

+ Response 200 (application/json)
    + Attributes (Mushroom)
