FORMAT: 1A
HOST: http://harvesters.whitecrestmushrooms.com/

# Whitecrest Mushrooms

This API lists all the harvesters associated with a site, sends information about hardware status, and shows data about picking, packing, and mushroom growing.


# Group Harvesters

A harvester is a single unit consisting of a lift, cart, scale and a packer. Inside a harvester there are mushrooms growing on beds, spread over many different vertical levels.

## Harvesters Collection [/harvesters]


### List all Harvesters [GET]

+ Attributes
    + id (number) - ID of the harvester in the form of an integer
    + name (string) - Descriptor of the harvester
    

This route displays all Harvesters on a site, and includes their name, ID, and status.

+ Response 200 (application/json)

        [
            {
                "name": "Harvester1",
                "id": 1,
                "status": 1,
            },
            {
                "name": "Harvester2",
                "id": 2,
                "status": 0,
            },
        ]

## Harvester [/harvesters/{id}]

+ Parameters
    + id (number) - ID of the harvester in the form of an integer


+ Attributes
    + id (number) - ID of the harvester in the form of an integer
    + status (enum[number])
        Status of the harvester in the form of an integer
        + 0: inactive
        + 1: active
    + name (string) - Descriptor of the harvester
    + level_id (number) - ID of the level the harvester is positioned at
    + bed_id (number)  - ID of the bed the harvester is positioned at


### Show a Harvester [GET]

This route exposes a single Harvester, shows the current level and bed position, and shows the status.

+ Request (application/json)

        {
            "id": 1,
        }

+ Response 200 (application/json)

    + Body
        
            {
                "name": "Harvester1",
                "level_id": 10,
                "bed_id": 40,
            }

# Group Levels

A Level is a horizontal collection of beds, located on a harvester.

## Level [/harvesters/{harvester_id}/levels/{id}]


## Levels Collection [/harvesters/{harvester_id}/levels]

This route displays all Levels on an individual Harvester, and includes their name and ID.

+ Attributes (object)
    + id (number) - ID of the level in the form of an integer
    + status (enum[number])
    Status of the level in the form of an integer
        + 0: inactive
        + 1: active
    + position (number) - Where the level is located vertically

### List all Levels [GET]


+ Parameters
    + id (number) - ID of harvester in the form of an integer

+ Response 200 (application/json)




    + Body
    
        [
            {
                "name": "Harvester1",
                "id": 1,
            },
            {
                "name": "Harvester2",
                "id": 2,
            },
        ]


# Group Lifts

## Lift  [/harvesters/{harvester_id}/lift]

# Group Packers

## Packer [/harvesters/{harvester_id}/packer]

# Group Carts

## Cart [/harvesters/{harvester_id}/cart]

+ Parameters
    + harvester_id (number) - ID of the harvester in the form of an integer
    
### Show a cart [GET]

This route exposes a the cart of a single Harvester.

+ Request (application/json)

        {
            "harvester_id": "1",
        }

+ Response 200 (application/json)

    + Headers

            Location: /harvesters/1/cart

    + Body
        
            {
                "id": "1",
                "level_id": "10",
                "status": "1"
            }
            
# Group Scales

## Scale [/harvesters/{harvester_id}/scale]

### Show a scale [GET]

This route exposes the Scale of a single Harvester.

+ Request (application/json)

        {
            "harvester_id": "1",
        }

+ Response 200 (application/json)

    + Headers

            Location: /harvesters/1/scale

    + Body
        
            {
                "id": "1",
                "current_output": "0.145",
                "status": "1"
                
            }