FORMAT: 1A
HOST: http://growers.whitecrestmushrooms.com/

# Whitecrest Mushrooms

This API lists all the growers associated with a site, sends information about hardware status, and shows data about picking, packing, and mushroom growing.

## Endpoints and API Access

For ItemPath (or any other application) to access data from the grower, an endpoint structure will need to be set up. Either the growers each will need to be connected to the internet and have an endpoint where this API is accesible, or each site will need to have a global processor to take data from the growers and provide a single endpoint to connect to.

## Core Concepts & Routes


### Hardware

* *Grower:* A grower is a single unit consisting of a lift, cart, scale and a harvester. Inside a grower there are mushrooms growing on beds, spread over many different vertical levels.
    * *Scale:* The scale weighs each packed bin of mushrooms.
    * *Lift:* The lift is the apparatus that moves the harvester between levels.
    * *Harvester:* The robotic arm that grabs mushrooms off of a bed and brings them to a packer.
* *Level:* A level is a collection of beds stacked vertically in a a grower.
* *Bed:* A bed is a soil area on a level where mushrooms are grown.
* *Mushroom:* Mushrooms grow on a bed.
* *Lug:* The bin that contains trays of mushrooms.
* *Tray:* A tray is where harvested mushrooms are placed on, and are put into lugs.

### Events

* *Harvest:* The action of picking a mushroom.
* *Scan:* When the grower records mushroom changes on a bed.
* *Test:* When a bed's temperature, pH, moisture, and humidity is recorded.
* *Pack:* The action of putting a tray into a lug.
* *Release:* When the lug is sent from the grower.


# Group Growers

A grower is a machine that picks and packs mushrooms.  A grower is a single unit consisting of a lift, cart, scale and a packer. Inside a grower there are mushrooms growing on beds, spread over many different vertical levels. There can be multiple growers on a site.

## Grower [/growers/{id}]

+ Parameters
    + id (number) - The ID of the desired grower.

+ Attributes (object)
    + id (number) - ID of the grower in the form of an integer
    + status (enum[number])
        Status of the grower in the form of an integer
        + Members
            + 0: inactive
            + 1: active
    + name (string) - Description of the grower
    + level_id (number) - ID of the level the grower is positioned at
    + bed_id (number) - ID of the bed the grower is positioned at
    + levels (number) - the number of levels in the grower
    + right_hand (boolean) - if the packer is on the left or right side of the grower 

### Retrieve a Grower [GET]

+ Response 200 (application/json)
    + Attributes (Grower)

### List all Growers [GET /growers{?limit}]

+ Parameters
    + limit (number, optional)

        A limit on the number of objects to be returned. Limit can range
        between 1 and 100 items.

        + Default: `25`

+ Response 200 (application/json)
    + Attributes (array[Grower])


# Group Levels

A level is a collection of beds stacked vertically in a a grower.

## Level [/levels/{id}]

+ Parameters
    + id (number) - The ID of the desired level.

+ Attributes (object)
    + id: 1 (number, required)
    + position: 0 (number, required) - vertical location of level
    + beds: [1,2,3,4] (array[number]) - array of bed ID's in level

### Retrieve a Level [GET]

+ Response 200 (application/json)
    + Attributes (Level)

### List all Levels on Grower [GET /grower/{grower_id}/levels{?limit}]
Returns a list of your Levels on a specific grower, in order of position.

+ Parameters
    + grower_id (number) - the ID of the grower.
    + limit (number, optional)

        A limit on the number of objects to be returned. Limit can range
        between 1 and 100 items.

        + Default: `25`

+ Response 200 (application/json)
    + Attributes (array[Level])

# Group Beds

A bed is a soil area on a level where mushrooms are grown.

## Bed [/beds/{id}]

+ Parameters
    + id (number) - The ID of the desired bed.

+ Attributes (object)
    + id: 1 (number, required)
    + position: 0 (number, required) - horizontal location of bed on a level
    + width: 24 (number) - width of bed in cm
    + height: 96 (number) - height of bed in cm
    + level_id: 1 (number) - the ID of the level the bed is located on
    + ph: 8 (number) - the current pH level
    + temperature: 276 (number) - the current temperature

### Retrieve a Bed [GET]

+ Response 200 (application/json)
    + Attributes (Bed)

### List all Beds [GET /beds{?limit}]

+ Parameters
    + limit (number, optional)

        A limit on the number of objects to be returned. Limit can range
        between 1 and 100 items.

        + Default: `25`

+ Response 200 (application/json)
    + Attributes (array[Bed])
    
### List all Beds on Level [GET /levels/{level_id}/beds{?limit}]

+ Parameters
    + level_id: 1 (number) - The ID of the level where the beds are.
    + limit (number, optional)

        A limit on the number of objects to be returned. Limit can range
        between 1 and 100 items.

        + Default: `25`

+ Response 200 (application/json)
    + Attributes (array[Bed])
    
### List all Beds on Grower [GET /growers/{grower_id}/beds{?limit}]

+ Parameters
    + grower_id: 1 (number) - The ID of the grower where the beds are.
    + limit (number, optional)

        A limit on the number of objects to be returned. Limit can range
        between 1 and 100 items.

        + Default: `25`

+ Response 200 (application/json)
    + Attributes (array[Bed])

# Group Mushrooms

A mushroom is located on a bed, in a level, and on a grower.

## Mushroom [/mushrooms/{id}]


+ Parameters
    + id (number) - The ID of the desired mushroom.

+ Attributes (object)
    + id: 1 (number, required)
    + x-coordinate: 14 (number, required) - x position on bed
    + y-coordinate: 35 (number, required) - y position on bed
    + size: 3 (number)
    + rotation: 264 (number) - rotation in degrees
    + is_cluster: true (boolean)
    + maturity_time: 15593060634745 (number) - date stamp of when the mushroom is ready to be picked
    + tray_id: 1 (number, optional) - the tray ID where the mushroom was harvested
    + bed_id: 1 (number, optional) - the bed ID where the mushroom is growing
    + grower_id: 1 (number) - the grower the mushroom was in

### Retrieve a Mushroom [GET]

+ Response 200 (application/json)
    + Attributes (Mushroom)

### List all Mushrooms [GET /mushrooms{?limit}]

+ Attributes (array[mushrooms])

+ Parameters
    + limit (number, optional)

        A limit on the number of objects to be returned. Limit can range
        between 1 and 500 items.

        + Default: `50`

+ Response 200 (application/json)
    + Attributes (Mushroom)

### List all Mushrooms on Grower [GET /growers/{grower_id}/mushrooms{?limit}]

+ Attributes (array[mushrooms])

+ Parameters
    + grower_id: 1 (number) - the ID of the grower
    + limit (number, optional)

        A limit on the number of objects to be returned. Limit can range
        between 1 and 500 items.

        + Default: `50`

+ Response 200 (application/json)
    + Attributes (Mushroom)
    
### List all Mushrooms on Bed [GET /beds/{bed_id}/mushrooms{?limit}]

+ Attributes (array[mushrooms])

+ Parameters
    + bed_id: 1 (number) - the ID of the bed
    + limit (number, optional)

        A limit on the number of objects to be returned. Limit can range
        between 1 and 500 items.

        + Default: `50`

+ Response 200 (application/json)
    + Attributes (Mushroom)

### List all Mushrooms on Tray [GET /trays/{tray_id}/mushrooms{?limit}]

+ Attributes (array[mushrooms])

+ Parameters
    + tray_id: 1 (number) - the ID of the tray
    + limit (number, optional)

        A limit on the number of objects to be returned. Limit can range
        between 1 and 500 items.

        + Default: `50`

+ Response 200 (application/json)
    + Attributes (Mushroom)

    
# Group Lugs

A lug is a reusable bin where trays are placed into.

## Lug [/lugs/{id}]


+ Parameters
    + id (number) - The ID of the desired lug.

+ Attributes (object)
    + id: 1 (number, required)
    + unique_identifier: o3452onfew529 (string)
    + grower_id: 1 (number)
    
### Retrieve a Lug [GET]

+ Response 200 (application/json)
    + Attributes (Lug)

### List all Lugs [GET  /lugs{?limit}]

+ Attributes (array[lugs])

+ Parameters
    + limit (number, optional)

        A limit on the number of objects to be returned. Limit can range
        between 1 and 500 items.

        + Default: `50`

+ Response 200 (application/json)
    + Attributes (Lug)
    
# Group Trays

A tray is where mushrooms are harvested and deposited.

## Tray [/trays/{id}]

+ Parameters
    + id (number) - The ID of the desired tray.

+ Attributes (object)
    + id: 1 (number, required)
    + unique_identifier: ot25o52o7kd091 (string)
    + lug_id: 1 (number)
    
### Retrieve a Tray [GET]

+ Response 200 (application/json)
    + Attributes (Tray)

### List all Trays [GET /trays{?limit}]

+ Attributes (array[trays])

+ Parameters
    + limit (number, optional)

        A limit on the number of objects to be returned. Limit can range
        between 1 and 500 items.

        + Default: `50`

+ Response 200 (application/json)
    + Attributes (Tray)
    
# Group Harvest

A harvest is an event where a mushroom gets picked.

## Harvest [/trays/{id}]

+ Parameters
    + id (number) - The ID of the desired harvest.

+ Attributes (object)
    + id: 1 (number, required)
    + mushroom_id: 1 (number)
    + tray_id: 1 (number)
    + lug_id: 1 (number)
    + harvested_at: 350043582064 (number) - the timestamp when the harvest took place
    
### Retrieve a Harvest [GET]

+ Response 200 (application/json)
    + Attributes (Tray)

### List all Harvests [GET /harvests{?limit}]

+ Attributes (array[harvests])

+ Parameters
    + limit (number, optional)

        A limit on the number of objects to be returned. Limit can range
        between 1 and 1000 items.

        + Default: `100`

+ Response 200 (application/json)
    + Attributes (Harvest)
    
### List all Harvests on Grower [GET growers/{grower_id}/harvests{?limit}]

+ Attributes (array[harvests])

+ Parameters
    + grower_id: 1 (number)
    + limit (number, optional)

        A limit on the number of objects to be returned. Limit can range
        between 1 and 1000 items.

        + Default: `100`

+ Response 200 (application/json)
    + Attributes (Harvest)

# Group Scan

A scan is when a mushroom size and growing amount is updated.

## Scan [/scans/{id}]

+ Parameters
    + id (number) - The ID of the desired scan.

+ Attributes (object)
    + id: 1 (number, required)
    + bed_id: 1 (number)
    + mushroom_id: 1 (number)
    + x-coordinate: 14 (number, required) - x position on bed
    + y-coordinate: 35 (number, required) - y position on bed
    + size: 3 (number)
    + rotation: 264 (number) - rotation in degrees
    + is_cluster: true (boolean)
    + scanned_at: 350043582064 (number) - the timestamp when the scan took place
    
### Retrieve a Scan [GET]

+ Response 200 (application/json)
    + Attributes (Scan)

### List all Scans [GET /scans{?limit}]

+ Attributes (array[scans])

+ Parameters
    + limit (number, optional)

        A limit on the number of objects to be returned. Limit can range
        between 1 and 1000 items.

        + Default: `100`

+ Response 200 (application/json)
    + Attributes (Harvest)